version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: weekly
    time: "23:00"
  open-pull-requests-limit: 99
  target-branch: maintenance/dep-update
  ignore:
  - dependency-name: org.springframework.boot
    versions:
    - 2.4.2
    - 2.4.3
    - 2.4.4
  - dependency-name: com.dlsc.preferencesfx:preferencesfx-core
    versions:
    - 11.7.0
  - dependency-name: org.controlsfx:controlsfx
    versions:
    - 11.0.3
  - dependency-name: org.junit.jupiter:junit-jupiter
    versions:
    - 5.7.0
