language: java
dist: trusty
sudo: false
install: true

addons:
  sonarcloud:
    organization: "adyel-github"
    token:
      secure: SONAR_TOKEN
      
jdk:
  - oraclejdk8
script:
  - ./gradlew sonarqube -Dsonar.projectKey=Adyel_ServerSam -Dsonar.organization=adyel-github -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=6247954df47068d34c7d5c3ee67f688b0e724b17

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
    - '$HOME/.gradle'
    - '.gradle'